TRAIN:
  ENABLE: False
  DATASET: ego4dhand
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: ~/outputs/exp-hparams-wd=1e-3/checkpoints/checkpoint_epoch_00017.pyth
  CHECKPOINT_TYPE: pytorch
  MODE: train
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: ~/ego4d_data/
  PATH_LABEL_SEPARATOR: ' '
  Resolution: 4
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: cosine
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  TWO_STREAM: True
  FLOW_ONLY: False
  NUM_CLASSES: 20
  ARCH: i3d
  MODEL_NAME: TwoStreamI3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  PRE_TRAINED: # i3d_r50
TEST:
  ENABLE: True
  DATASET: ego4dhand
  BATCH_SIZE: 64
  SAVE_RESULTS_PATH: output.pkl
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_FILE_PATH: "~/outputs/exp-two_stream-epoch=20-trainval/checkpoints/checkpoint_epoch_00017.pyth"
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  CONFUSION_MATRIX:
    ENABLE: False
  HISTOGRAM:
    ENABLE: False
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ~/outputs/exp-two_stream-epoch=20-trainval
